apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: VPC
metadata:
  name: example-network
spec:
  cidrBlock: "10.20.0.0/16"
  enableDnsSupport: true
  enableDnsHostnames: true
  instanceTenancy: default
  tags:
    - key: Name
      value: my-super-vpc2
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIP
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eip-sample
spec:
  vpcName: example-network
  tags:
    - key: Name
      value: BrandNewIP
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIP
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eip-sample-for-nat
spec:
  vpcName: example-network
  tags:
    - key: Name
      value: BrandNewIPforNAT
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIP
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eip-sample-for-ec2
spec:
  vpcName: example-network
  tags:
    - key: Name
      value: BrandNewIPforEC2
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-a
spec:
  vpcName: example-network
  availabilityZone: "us-west-2a"
  cidrBlock: "10.20.110.0/24"
  tags:
   - key: Name
     value: public-a
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-b
spec:
  vpcName: example-network
  availabilityZone: "us-west-2b"
  cidrBlock: "10.20.120.0/24"
  tags:
   - key: Name
     value: public-b
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-c
spec:
  vpcName: example-network
  availabilityZone: "us-west-2c"
  cidrBlock: "10.20.130.0/24"
  tags:
   - key: Name
     value: public-c
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sample-ec2-instance
spec:
  imageId: ami-6cd6f714 #Amazon Linux
  instanceType: t2.micro
  subnetName: example-network-public-a
  userData: touch /root/test.txt
  tags:
    - key: Name
      value: "Test Instance"
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: RouteTable
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: routetable-sample
spec:
  vpcName: example-network
  tags:
    - key: sample-key
      value: sample-value
    - key: Name
      value: SampleRouteTable
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: internetgateway-sample
spec:
  tags:
    - key: Name
      value: SampleInternetGateway
  vpcName: example-network
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Route
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: route-sample
spec:
  destinationCidrBlock: "192.168.1.0/24"
  routeTableName: routetable-sample
  gatewayName: internetgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIPAssociation
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eipassociation-sample
spec:
  allocationName: eip-sample-for-ec2
  instanceName: sample-ec2-instance
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGatewayAttachment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: internetgatewayattachment-sample
spec:
  vpcName: example-network
  internetGatewayName: internetgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: NATGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: natgateway-sample
spec:
  subnetName: example-network-public-a
  eipAllocationName: eip-sample-for-nat
  tags:
    - key: Name
      value: Amazing-NAT-Gateway
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Volume
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: volume-sample
spec:
  availabilityZone: us-west-2a
  size: 8
  volumeType: gp2
  tags:
    - key: Name
      value: sample-volume
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2VolumeAttachment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: volumeattachment-sample
spec:
  devicePath: /dev/xvdb
  ec2InstanceName: sample-ec2-instance
  volumeName: volume-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2KeyPair
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ec2keypair-sample
spec:
  ec2KeyPairName: sample-keypair
