apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EC2SecurityGroup
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ec2securitygroup-sample
spec:
  ec2SecurityGroupName: sample-securitygroup
  vpcName: example-network
  description: an aws ec2 security group
  tags:
    - key: Project
      value: testing
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: VPC
metadata:
  name: example-network
spec:
  cidrBlock: "10.20.0.0/16"
  enableDnsSupport: true
  enableDnsHostnames: true
  instanceTenancy: default
  tags:
    - key: Name
      value: my-super-vpc2
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-a
spec:
  vpcName: example-network
  availabilityZone: "us-west-2a"
  cidrBlock: "10.20.110.0/24"
  tags:
   - key: Name
     value: public-a
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: RouteTable
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: routetable-sample
spec:
  vpcName: example-network
  tags:
    - key: sample-key
      value: sample-value
    - key: Name
      value: SampleRouteTable
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Route
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: route-sample1
spec:
  destinationCidrBlock: 10.11.0.0/16
  routeTableName: routetable-sample
  gatewayName: internetgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Route
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: route-sample2
spec:
  destinationCidrBlock: 0.0.0.0/0
  routeTableName: routetable-sample
  natGatewayName: natgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: NATGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: natgateway-sample
spec:
  subnetName: example-network-public-a
  eipAllocationName: nat-eip
  tags:
    - key: Name
      value: Amazing-NAT-Gateway
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIP
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nat-eip
spec:
  vpcName: example-network
  tags:
    - key: Name
      value: NATGatewayEIP
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGateway
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: internetgateway-sample
spec:
  tags:
    - key: Name
      value: InternetGateway
  vpcName: example-network
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: InternetGatewayAttachment
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: attachgateway-sample
spec:
  vpcName: example-network
  internetGatewayName: internetgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Route
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: route-sample3
spec:
  destinationCidrBlock: 10.10.0.0/16
  routeTableName: routetable-sample
  natGatewayName: natgateway-sample
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: AuthorizeEC2SecurityGroupIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: shortname-sample
spec:
  ruleName: shortname
  sourceCidrIp: 0.0.0.0/0
  ec2SecurityGroupName: ec2securitygroup-sample
  fromPort: 22
  toPort: 22
  ipProtocol: tcp
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: AuthorizeEC2SecurityGroupIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: stillshortname-sample
spec:
  ruleName: stillshortname
  sourceCidrIp: 0.0.0.0/0
  ec2SecurityGroupName: ec2securitygroup-sample
  fromPort: 80
  toPort: 80
  ipProtocol: tcp
---
apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: AuthorizeEC2SecurityGroupIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: longerrulenamehere
spec:
  ruleName: longerrulenamehere
  sourceCidrIp: 0.0.0.0/0
  ec2SecurityGroupName: ec2securitygroup-sample
  fromPort: 443
  toPort: 443
  ipProtocol: tcp
