apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: authorizeec2securitygroupingresses.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: AuthorizeEC2SecurityGroupIngress
    plural: authorizeec2securitygroupingresses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            fromPort:
              format: int64
              type: integer
            ipProtocol:
              type: string
            sourceCidrIp:
              type: string
            toPort:
              format: int64
              type: integer
          required:
          - sourceCidrIp
          - fromPort
          - toPort
          - ipProtocol
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
