apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: routetableassociations.ecc.aws.gotopple.com
spec:
  group: ecc.aws.gotopple.com
  names:
    kind: RouteTableAssociation
    plural: routetableassociations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            routeTableName:
              type: string
            subnetName:
              type: string
          required:
          - routeTableName
          - subnetName
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
