apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: AuthorizeEC2SecurityGroupIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ingressrule-walkthrough-ssh
  namespace: kloudformation
spec:
  ruleName: ssh
  sourceCidrIp: 0.0.0.0/0
  ec2SecurityGroupName: ec2securitygroup-walkthrough
  fromPort: 22
  toPort: 22
  ipProtocol: tcp
