apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: EIP
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: eip-sample-for-ec2
spec:
  vpcName: example-network
  tags:
    - key: Name
      value: BrandNewIPforEC2
