apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: AuthorizeEC2SecurityGroupIngress
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: authorizeec2securitygroupingress-sample
spec:
  # Add fields here
  foo: bar
