apiVersion: ecc.aws.gotopple.com/v1alpha1
kind: Subnet
metadata:
  name: example-network-public-b
spec:
  vpcName: example-network
  availabilityZone: "us-west-2b"
  cidrBlock: "10.20.120.0/24"
  tags:
   - key: Name
     value: public-b
